# Generated by Django 2.0.4 on 2018-06-02 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basket', '0002_auto_20180424_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coach',
            name='dv',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='coach',
            name='rut',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='dv',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='player',
            name='rut',
            field=models.PositiveIntegerField(),
        ),
    ]
