# Generated by Django 2.0.4 on 2018-06-02 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_auto_20180602_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='team',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basket.Team'),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.PositiveIntegerField(help_text='Peso en kilos'),
        ),
    ]
