# Generated by Django 2.0.4 on 2018-06-03 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0004_auto_20180602_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TeamCompose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basket.Coach')),
                ('match', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basket.Match')),
                ('players', models.ManyToManyField(default=None, to='basket.Player')),
            ],
        ),
    ]
