# Generated by Django 2.0.4 on 2018-06-04 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0005_match_teamcompose'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Team1', to='basket.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Team2', to='basket.Team'),
        ),
    ]
